### ISSUE TITLE
OAuth Rest Example - Zuul Angular App is not working

### ISSUE THREAD

**Issue by d3minem** [Baeldung/spring-security-oauth#186]
The angular zuul app is not working properly. When I hit the login in angular app: `http://localhost:8089`. It redirects to: `http://localhost:8080/auth/code` with error html page: saying that **client_id** is missing. `Missing parameters: client_id`

**Zuul Debugging:**

As I'm new to Zuul, so I found that we're using the **SimpleHostRoutingFilter** because of **url** defined in the route mapping. So the CustomPreZuulFilter append all the request params in the url before it hit the route host url (not worked).

**Note:** So I just append the request params in the route url mapping directly because the `CustomPreZuulFilter` code snippet for query params is not working.

```
auth/code:
      path: /auth/code/**
      sensitiveHeaders:
      url: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/auth?response_type=code&scope=read&client_id=newClient&redirect_uri=http://localhost:8080/auth/redirect/
```
 
Now I can see in the logs that host route has all the query params:
```
2020-04-18 13:45:55.529  INFO 62190 --- [nio-8080-exec-2] com.baeldung.config.CustomPreZuulFilter  : Zuul Pre Filter [Host Route]: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/auth?response_type=code&scope=read&client_id=newClient&redirect_uri=http://localhost:8080/auth/redirect/
2020-04-18 13:45:55.530  INFO 62190 --- [nio-8080-exec-2] com.baeldung.config.CustomPreZuulFilter  : Zuul Pre Filter [Host Route] Query: response_type=code&scope=read&client_id=newClient&redirect_uri=http://localhost:8080/auth/redirect/
```
The authorisation server basically logs the error:
```
2020-04-18 13:55:49.504  WARN 60413 --- [nio-8083-exec-1] org.keycloak.events                      : type=LOGIN_ERROR, realmId=baeldung, clientId=null, userId=null, ipAddress=127.0.0.1, error=invalid_request
```
Can you please look into this issue? and let me know if Zuul is properly configured. When I hit the host route with query params in browser, the authorisation server show me the login page correctly.
